name: Docker-GPR
description: Build, Tag and Push images from a Dockerfile to the GPR

inputs:
  repo-token:
    description: Github access token, use GITHUB_TOKEN.
    default: No token was provided.
    required: true
  image-name:
    description: The name of the Docker Image.
    required: true
  dockerfile-location:
    description: Where in the repo the Dockerfile is located
    default: .
    required: false
  tag:
    description: tag for Docker image
    default: ${{ github.sha }}
    required: false
outputs:
  imageUrl:
    description: Fully constructed URL to image for use when deploying

runs:
  using: "node12"
  main: main.js
