name: Remove Beta Release
description: Remove prerelease tags and deprecate on NPM

inputs:
  pull-request-fix:
    description: Fix for pull request to deprecate
    required: true

outputs:
  removed-git-tags:
    description: Github Tags Removed
  removed-npm-versions:
    description: NPM Versions Removed

runs:
  using: "node12"
  main: main.js
