name: Remove Prerelease
description: Remove prerelease tags and deprecate on NPM

inputs: 
  github-token:
    description: Github Token
    required: true
  pull-request-fix:
    description: Fix for pull request to deprecate
    required: true

outputs:
  removed-releases:
    description: Tags removed

runs:
  using: "node12"
  main: main.js
