name: Publish Beta

on:
  workflow_dispatch:

jobs:
  beta-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.head_ref != 'master' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Set git configs
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com

    - name: Create .npmrc file
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Increment
      run: npm version prerelease --preid='pr${{ github.event.number }}'

    - run: git push && git push --tags
