name: Deprecate Beta

on:
  pull_request:
    branches:
      - '*'

jobs:
  beta-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'

    - name: Create .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc

    - run: npm whoami

    - name: Deprecate beta version
      uses: ./package-remove-prerelease
      id: package-deprecate
      with: 
        github-token: ${{ github.token }}
        pull-request-fix: 'pr${{ github.event.number }}'

    - run: | 
        echo ${{ steps.package-deprecate.outputs.removed-releases }} 