name: Release
on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Semantic Release
      uses: storykit/semantic-release-action@master
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Notify slack
      if: steps.semantic.outputs.new_release_published == 'true'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C02P9AL9R\",\"text\":\"*Storykit Github Action Released!* :fire:\n===================\n${{ steps.semantic.outputs.new_release_notes }}\"}'